### ISSUE TITLE
LESS style updates are not propagating (Preact)

### ISSUE THREAD

**Issue by prayash** [mattdesl/threejs-app#2]
Hey Matt,

Super awesome repo, really digging the setup. I was wondering if you've run into issues with updating styles on the preact branch? I can see that the live reload is coming through but it doesn't apply the updated styles on save.

Right now, I've got it working by changing this portion of `bundler.js`:
```javascript
if (app) {
    attachShaderReload(app)
    app.on('watch', (ev, file) => {
      if (/\.(less)$/i.test(file)) {
        style.write() // <----- Added this line!
        app.reload(style.getCSSURL())
      }
    })
  }
```

Can submit a PR if this is the solution.

**Comment by mattdesl** [comment]
This is odd — I just tested on my machine and LESS updates are working fine without any changes.

The way it works is that LESS file changes trigger `app.reload`, which re-requests `style.css`. As a result, instead of just serving a static `style.css` file, the middleware responds with a less-ified version of `main.less`.

I'm on OSX 10.12.6, node@8.4.0 and npm@5.6.0. What platform/versions are you using?

**Comment by prayash** [comment]
Super strange. I'm on macOS 10.12.6, node@8.9.3 and npm@5.5.1. I just did a fresh clone and `yarn install`ed, and tried some style changes, and no dice. 

I can see that the stylesheet path updates looking at the style inspector, but the actual changes don't propagate. Posting a lo-fi gif below:

![screencast 2018-02-13 09-46-25](https://user-images.githubusercontent.com/3971101/36162396-95967494-10a3-11e8-9f1d-83594a7296d1.gif)
